[features]
seeds = false
skip-lint = false
[programs.devnet]
domichain_hello_world = "Ecr5UgGyJTnKraLRPYBXrK9RD7DfoVDYfSioVksnnfjA"
FIXME = true

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ajayvasisht/.config/domichain/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
